#!/bin/bash
cleanup () {
    docker-compose -f docker-compose.yaml -f test/docker-compose.test.yaml rm -svf
}
trap cleanup EXIT

docker-compose -f docker-compose.yaml -f test/docker-compose.test.yaml run --rm --name=template-golang-kubernetes-${GIT_HASH} test
